### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by DragonOfStendarr** [the-realest-stu/Dynamic-Trees-BOP#7]
There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dynamic Trees BOP (dynamictreesbop)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/ferreusveritas/dynamictrees/api/treedata/ILeavesProperties
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:584)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by ferreusveritas** [comment]
Upgrade to the latest version of Dynamic Trees 0.7.5c and remove any older versions of Dynamic Trees.

**Comment by DragonOfStendarr** [comment]
It's updated to that, still getting those crashes.

**Comment by ferreusveritas** [comment]
Please send a list of all mods you are using and their versions.  A screenshot of the mods directory would be fine.

**Comment by DragonOfStendarr** [comment]
let me test something, i think theres a issue with toughasnails

**Comment by DragonOfStendarr** [comment]
here was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dynamic Trees BOP (dynamictreesbop)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/ferreusveritas/dynamictrees/api/treedata/ILeavesProperties
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:584)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/ferreusveritas/dynamictrees/api/treedata/ILeavesProperties
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 36 more
Caused by: java.lang.ClassNotFoundException: com.ferreusveritas.dynamictrees.api.treedata.ILeavesProperties
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer toughasnails.asm.transformer.CropDecayTransformer@32f45e15 from coremod TANLoadingPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 44 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at toughasnails.asm.transformer.CropDecayTransformer.transform(CropDecayTransformer.java:50)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)

**Comment by DragonOfStendarr** [comment]
as you notice it does say its an issue with toughasnails and this mod. atleast what i read from it, but then again i might be mistaken.

**Comment by ferreusveritas** [comment]
Is there a reason why you're not fulfilling my request?

**Comment by DragonOfStendarr** [comment]
Nope, im saying its gonne be a hell of a job, considering its about 170 mods in there :) im uploading the stuff now.

**Comment by DragonOfStendarr** [comment]
https://imgur.com/a/tw756

**Comment by ferreusveritas** [comment]
Sorry to put you through that but I had to be sure.  I don't know you from Sam and I've had users swear they upgraded and did something weird instead.  The crash message heavily implies that the Dynamic Trees mod isn't installed at all or is an old version before the ILeavesProperties was implemented by the API.  Your screenshot shows that everything should be in working order.  This crash shouldn't be possible given that the only caller for Dynamic Trees API is currently the Dynamic Trees BoP add-on and it requires a version with ILeavesProperties.  You aren't by chance running the wrong launcher are you?

**Comment by DragonOfStendarr** [comment]
which launcher am i suppose to use? considering that it is my own private pack....

**Comment by ferreusveritas** [comment]
What I mean is that you may have multiple forge installations for different versions or setups and you mistakenly placed a mod in the wrong folder.  I suspect you are updating the mods in one folder and then launching a forge version for another set of mods and getting a crash message for something totally unrelated.

**Comment by ferreusveritas** [comment]
Any luck?

**Comment by ferreusveritas** [comment]
Assuming resolved
